### ISSUE TITLE
No results outputted in /results dir

### ISSUE THREAD

**Issue by mtaylorSF** [Eficode/Docker-Selenium-Example#2]
First off, thank u for this.  Been searching for examples and yours is by far the best found.

**Issue**:
after i ran `docker-compose run test-ff` nothing is available in the `/results` folder.

I did notice the following; `--outputdir /out`, should that be updated?
```
test-ff:
    build: robot
    command: -v BROWSER:ff --outputdir /out /tests
    volumes:
      - ./robot/tests:/tests:ro
      - ./results/ff:/out:rw
    depends_on:
      - demoapp
      - firefox
    networks:
      - selenium-grid
```
Same goes for the  `docker-compose run test-gc` command

Once again, thanks for the example.
